### ISSUE TITLE
Specify multiple build targets

### ISSUE THREAD

**Issue by ottumm** [briangreenery/bran#12]
Example:

```
win:
  default:
    - build server
  tests:
    - build tests
  all:
    - build all

linux:
  tests:
    - make test
  all:
    - make
```

  bran build {target} [host1 host2 ...]

bran would always build the same target across whichever hosts are specified and also have that target defined. If no hosts are specified, then bran would build on every host that has the target specified. If no target is specified, then bran would build the "default" target on whichever hosts have it specified.
